"""Create evidence-first artifacts for the fixed-point aggregation ablation.

The input is generated by ``run_dmcfe_sensitivity_ablation.py``.  Results are
descriptive: five seeded synthetic update sets are used to probe numerical
sensitivity, and each timing observation is a seven-repeat within-process
median for the non-secure reference backend.
"""

from __future__ import annotations

import argparse
import csv
import math
import statistics
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = (
    REPO_ROOT
    / "python/examples/federate/simulation/sp_fedavg_mnist_lr_example/results/dmcfe_sensitivity_ablation.csv"
)
DEFAULT_OUTPUT = REPO_ROOT / "analysis-output/chapter4_section3"
BASELINE = {"scale": 1 << 14, "clip_bound": 8.0, "chunk_size": 65536}
T_975_DF4 = 2.7764451051977987
OKABE_ITO = ("#0072B2", "#D55E00", "#009E73", "#CC79A7")


def load_rows(path: Path):
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    numeric_fields = {
        "seed": int,
        "clients": int,
        "coordinates": int,
        "scale": int,
        "clip_bound": float,
        "chunk_size": int,
        "chunks": int,
        "clipped_fraction": float,
        "max_abs_error": float,
        "mean_abs_error": float,
        "elapsed_ms_median": float,
        "elapsed_ms_min": float,
        "elapsed_ms_max": float,
        "timing_repeats": int,
    }
    for row in rows:
        for name, converter in numeric_fields.items():
            row[name] = converter(row[name])
    return rows


def summarize(rows, metric):
    values = [row[metric] for row in rows]
    mean = statistics.mean(values)
    sd = statistics.stdev(values) if len(values) > 1 else 0.0
    ci = T_975_DF4 * sd / math.sqrt(len(values)) if len(values) == 5 else float("nan")
    return {"n": len(values), "mean": mean, "sd": sd, "ci": ci, "median": statistics.median(values)}


def factor_rows(rows, factor):
    fixed = {key: value for key, value in BASELINE.items() if key != factor}
    selected = [row for row in rows if all(row[key] == value for key, value in fixed.items())]
    return {value: [row for row in selected if row[factor] == value] for value in sorted({row[factor] for row in selected})}


def format_sci(value):
    return f"{value:.3e}"


def format_pm(summary, scientific=False):
    formatter = format_sci if scientific else lambda value: f"{value:.3f}"
    return f"{formatter(summary['mean'])} ± {formatter(summary['sd'])}"


def save_figure(fig, output: Path):
    """Write a vector figure for the manuscript and a high-resolution preview."""
    fig.savefig(output, bbox_inches="tight")
    fig.savefig(output.with_suffix(".png"), dpi=600, bbox_inches="tight")


def write_csv_summary(output: Path, rows):
    factors = ("scale", "clip_bound", "chunk_size")
    metrics = ("max_abs_error", "mean_abs_error", "clipped_fraction", "elapsed_ms_median")
    with output.open("w", newline="", encoding="utf-8") as handle:
        fields = ["factor", "level", "metric", "n", "mean", "sd", "ci", "median"]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for factor in factors:
            for level, level_rows in factor_rows(rows, factor).items():
                for metric in metrics:
                    result = summarize(level_rows, metric)
                    writer.writerow({"factor": factor, "level": level, "metric": metric, **result})


def plot_error_sensitivity(output: Path, rows):
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.7), constrained_layout=True)
    for axis, factor, xlabel in zip(
        axes,
        ("scale", "clip_bound"),
        ("Scale factor q", "Clipping bound B"),
    ):
        groups = factor_rows(rows, factor)
        levels = list(groups)
        max_error = [summarize(groups[level], "max_abs_error") for level in levels]
        mean_error = [summarize(groups[level], "mean_abs_error") for level in levels]
        axis.errorbar(levels, [item["mean"] for item in max_error], yerr=[item["sd"] for item in max_error],
                      marker="o", color=OKABE_ITO[0], linewidth=1.6, capsize=3, label="Max. abs. error")
        axis.errorbar(levels, [item["mean"] for item in mean_error], yerr=[item["sd"] for item in mean_error],
                      marker="s", color=OKABE_ITO[1], linewidth=1.6, capsize=3, label="Mean abs. error")
        axis.set_xscale("log", base=2)
        axis.set_xticks(levels)
        if factor == "scale":
            axis.set_xticklabels([r"$2^{10}$", r"$2^{14}$", r"$2^{18}$"])
        else:
            axis.set_xticklabels([f"{level:g}" for level in levels])
        axis.set_yscale("log")
        axis.set_xlabel(xlabel)
        if factor == "scale":
            axis.set_ylabel("Error vs. unclipped float reference")
        axis.grid(alpha=0.25)
    axes[0].legend(fontsize=8, frameon=False)
    save_figure(fig, output)
    plt.close(fig)


def plot_reference_timing(output: Path, rows):
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.7), constrained_layout=True)
    chunk_groups = factor_rows(rows, "chunk_size")
    levels = list(chunk_groups)
    timing = [summarize(chunk_groups[level], "elapsed_ms_median") for level in levels]
    axes[0].errorbar(levels, [item["mean"] for item in timing], yerr=[item["sd"] for item in timing],
                     marker="o", color=OKABE_ITO[2], linewidth=1.6, capsize=3)
    axes[0].set_xscale("log", base=2)
    axes[0].set_xlabel("Chunk size")
    axes[0].set_ylabel("Reference-backend elapsed time (ms)")
    axes[0].grid(alpha=0.25)

    clip_groups = factor_rows(rows, "clip_bound")
    levels = list(clip_groups)
    clipping = [summarize(clip_groups[level], "clipped_fraction") for level in levels]
    axes[1].errorbar(levels, [item["mean"] * 100 for item in clipping],
                     yerr=[item["sd"] * 100 for item in clipping], marker="o",
                     color=OKABE_ITO[3], linewidth=1.6, capsize=3)
    axes[1].set_xscale("log", base=2)
    axes[1].set_xlabel("Clipping bound B")
    axes[1].set_ylabel("Clipped coordinates (%)")
    axes[1].grid(alpha=0.25)
    save_figure(fig, output)
    plt.close(fig)


def write_reports(output: Path, rows):
    by_scale = factor_rows(rows, "scale")
    by_clip = factor_rows(rows, "clip_bound")
    by_chunk = factor_rows(rows, "chunk_size")
    baseline_row = [row for row in rows if all(row[key] == value for key, value in BASELINE.items())]
    baseline = {metric: summarize(baseline_row, metric) for metric in (
        "max_abs_error", "mean_abs_error", "clipped_fraction", "elapsed_ms_median"
    )}
    scale_low = summarize(by_scale[min(by_scale)], "max_abs_error")
    scale_high = summarize(by_scale[max(by_scale)], "max_abs_error")
    clip_low = summarize(by_clip[min(by_clip)], "max_abs_error")
    clip_high = summarize(by_clip[max(by_clip)], "max_abs_error")
    chunk_fast = min((summarize(group, "elapsed_ms_median")["mean"], level) for level, group in by_chunk.items())
    chunk_slow = max((summarize(group, "elapsed_ms_median")["mean"], level) for level, group in by_chunk.items())

    analysis = f"""# Analysis Report: Fixed-Point Aggregation Sensitivity

## Analysis question

For the non-secure `chunked-reference` backend, how do fixed-point scale $q$, coordinate clipping bound $B$, and chunk size affect numerical deviation from an **unclipped floating-point weighted average**, clipping incidence, and reference implementation elapsed time?

## Evidence and comparison unit

- Input: `python/examples/federate/simulation/sp_fedavg_mnist_lr_example/results/dmcfe_sensitivity_ablation.csv` (300 rows).
- Design: 3 scale levels × 4 clipping bounds × 5 chunk sizes × 5 seeded synthetic update sets; 8 clients, 32,768 coordinates, and fixed integer client weights per seed.
- Unit for numerical summaries: one seed-level aggregation result ($n=5$ per plotted factor level after holding the other two factors at $q=2^{{14}}$, $B=8$, chunk size 65,536).
- Unit for timing summaries: one seed-level median of 7 warm timing repetitions, measured within one Python process.
- Timing environment: Windows 11; Python 3.12.14; PyTorch 2.14.0+cpu; 8 PyTorch CPU threads. It is distinct from the GPU training environment reported in Chapter 4.1.
- Uncertainty: mean ± sample SD; 95% t intervals are listed in the appendix only. No significance test is reported: $n=5$ is small, timings are same-process measurements, and synthetic seeds are sensitivity probes rather than independent training runs.

## Key findings

1. With $B=8$ and chunk size 65,536, increasing $q$ from $2^{{10}}$ to $2^{{18}}$ changes the mean maximum absolute error from {format_sci(scale_low['mean'])} to {format_sci(scale_high['mean'])}; this is the expected reduction in rounding resolution error under an inactive clipping bound.
2. With $q=2^{{14}}$ and chunk size 65,536, reducing $B$ from 8 to 0.5 changes the mean maximum absolute error from {format_sci(clip_high['mean'])} to {format_sci(clip_low['mean'])}. The associated clipped-coordinate fraction is reported directly in the summary table; this comparison conflates clipping bias and quantization error by design because the error reference is unclipped.
3. At the baseline configuration, the numerical summary is maximum error {format_pm(baseline['max_abs_error'], scientific=True)}, mean error {format_pm(baseline['mean_abs_error'], scientific=True)}, clipped fraction {format_pm(baseline['clipped_fraction'])}, and reference-backend elapsed time {format_pm(baseline['elapsed_ms_median'])} ms.
4. Among the tested chunk sizes, the fastest mean reference-backend elapsed time occurs at {chunk_fast[1]:,} coordinates/chunk ({chunk_fast[0]:.3f} ms); the slowest occurs at {chunk_slow[1]:,} ({chunk_slow[0]:.3f} ms). This is a property of this CPU loop and allocator/runtime state, not a cryptographic benchmark.

## Claim Candidates

- Claim: Increasing the scale factor reduces the measured deviation when clipping is inactive in this synthetic fixed-point probe.
  - Source evidence: `figure-01-error-sensitivity.pdf`, factor-held-constant rows in the raw CSV.
  - Allowed wording: “在该定点参考聚合探针中，较大的缩放因子对应更小的数值偏差。”
  - Forbidden stronger wording: “更大的缩放因子必然提升端到端训练精度。”
  - Uncertainty: only five synthetic update sets; no training-accuracy outcome is measured.
  - Next check: repeat on saved per-round model updates from multi-seed training.
  - Decision: keep.

- Claim: A smaller clipping bound produces greater deviation from the unclipped reference when more coordinates are clipped.
  - Source evidence: raw clipping fractions and `figure-01-error-sensitivity.pdf`.
  - Allowed wording: “较小裁剪阈值在本探针中引入更明显的相对无裁剪参考偏差。”
  - Forbidden stronger wording: “该阈值损害最终模型性能。”
  - Uncertainty: no learning trajectory or generalization metric is included.
  - Next check: attach the same diagnostic to model-training rounds.
  - Decision: keep.

- Claim: Chunk size changes `chunked-reference` elapsed time under a fixed CPU workload.
  - Source evidence: `figure-02-reference-timing.pdf`.
  - Allowed wording: “分块长度影响参考实现的本地聚合耗时。”
  - Forbidden stronger wording: “分块长度决定功能加密计算开销” or “方案密码计算效率为 X ms.”
  - Uncertainty: no encryption, key generation, ciphertext serialization, communication, or peak memory is measured.
  - Next check: benchmark a production-reviewed DMCFE-IP backend by protocol stage.
  - Decision: keep with boundary.
"""

    stats = """# Statistical Appendix: Fixed-Point Aggregation Sensitivity

## Validity and statistical scope

The raw file has 300 complete rows, each tagged `backend=chunked-reference`; no missing values were found. Every configuration is evaluated on the same five synthetic seed IDs (0–4), so factor-level numerical comparisons are paired by seed. The per-row elapsed-time field is the median of seven post-warmup calls in a single process. It is not an independent timing replicate and it excludes encryption, functional-key work, serialization, network transfer, and peak-memory measurement.

Timing environment: Windows 11; Python 3.12.14; PyTorch 2.14.0+cpu; 8 PyTorch CPU threads. This CPU microbenchmark is separate from the Chapter 4.1 GPU training environment.

Because there are only five synthetic seed-level numerical observations per factor level and the timing observations are benchmark medians, this analysis deliberately makes no null-hypothesis claim, normality test, p-value, or multiple-comparison decision. The analysis reports all levels, sample SD, and 95% t intervals for descriptive uncertainty; it does not treat the five seeds as five independent federated-training runs.

## Exact numeric summary (one factor varied; remaining parameters fixed at q=2^14, B=8, chunk=65,536)

| Factor | Level | Max abs. error (mean ± SD) | Mean abs. error (mean ± SD) | Clipped fraction (mean ± SD) | Reference elapsed time, ms (mean ± SD) |
|---|---:|---:|---:|---:|---:|
"""
    for factor, groups in (("q", by_scale), ("B", by_clip), ("chunk", by_chunk)):
        for level, group in groups.items():
            max_error = summarize(group, "max_abs_error")
            mean_error = summarize(group, "mean_abs_error")
            clipped = summarize(group, "clipped_fraction")
            timing = summarize(group, "elapsed_ms_median")
            stats += (
                f"| {factor} | {level:,} | {format_pm(max_error, scientific=True)} | "
                f"{format_pm(mean_error, scientific=True)} | {format_pm(clipped)} | {format_pm(timing)} |\n"
            )
    stats += """

## 95% t interval half-widths

The summary CSV contains the 95% t interval half-width for every metric and factor level (`summary.csv`, $t_{0.975,4}=2.776$). These intervals characterize variation across the five generated update sets only; they do not establish population performance, efficiency, or cryptographic cost.

## Blocked claims

- No claim about functional-encryption latency, throughput, communication volume, or memory footprint is valid from this benchmark.
- No claim about end-to-end training accuracy, convergence, or optimal parameter values is valid from these synthetic-vector experiments.
- No cross-method superiority claim or significance claim is valid.
"""
    catalog = """# Figure Catalog: Fixed-Point Aggregation Sensitivity

## figure-01-error-sensitivity.pdf / figure-01-error-sensitivity.png

- Purpose: isolate numerical sensitivity to scale factor and clipping bound while holding the other two parameters fixed.
- Data source: five seed-level rows per point from `dmcfe_sensitivity_ablation.csv`.
- File roles: the PDF is the vector manuscript figure; the 600-DPI PNG is a Markdown preview of the same plot.
- Caption requirements: state the fixed settings, error reference (unclipped floating-point weighted average), and that error bars are sample SD over five synthetic update sets.
- Key observation: scale affects rounding resolution under a loose clipping bound; smaller clipping bounds produce larger error relative to the unclipped reference.
- Interpretation checklist: distinguish clipping bias from quantization error; do not generalize to training accuracy.

## figure-02-reference-timing.pdf / figure-02-reference-timing.png

- Purpose: show the CPU execution-time sensitivity of the non-secure reference implementation and the clipping incidence under the same probe.
- Data source: timing medians from seven post-warmup calls per seed, summarized over five seeds.
- File roles: the PDF is the vector manuscript figure; the 600-DPI PNG is a Markdown preview of the same plot.
- Caption requirements: state that error bars are sample SD and timing is not functional-encryption cost.
- Key observation: chunk size changes reference-loop time; clipping incidence decreases as the clipping bound grows.
- Interpretation checklist: do not infer encryption, communication, memory, or deployed-system overhead.
"""
    (output / "analysis-report.md").write_text(analysis, encoding="utf-8")
    (output / "stats-appendix.md").write_text(stats, encoding="utf-8")
    (output / "figure-catalog.md").write_text(catalog, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rows = load_rows(args.input)
    if len(rows) != 300:
        raise ValueError(f"expected 300 rows, found {len(rows)}")
    if {row["backend"] for row in rows} != {"chunked-reference"}:
        raise ValueError("unexpected backend label")
    args.output.mkdir(parents=True, exist_ok=True)
    figures = args.output / "figures"
    figures.mkdir(exist_ok=True)
    write_csv_summary(args.output / "summary.csv", rows)
    plot_error_sensitivity(figures / "figure-01-error-sensitivity.pdf", rows)
    plot_reference_timing(figures / "figure-02-reference-timing.pdf", rows)
    write_reports(args.output, rows)
    print(f"wrote analysis bundle to {args.output}")


if __name__ == "__main__":
    main()
